# Generated by Django 3.2.7 on 2021-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_navigate',
            field=models.CharField(default='www.google.com', max_length=200),
        ),
    ]
