# Generated by Django 3.2.7 on 2021-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_button_navigate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_navigate',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
    ]
