# Generated by Django 3.2.7 on 2021-09-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='https://youtube.com/', max_length=255),
            preserve_default=False,
        ),
    ]
